-- Portal ITSM Service Desk v7 — aplicado uma vez se public.clientes não existir
CREATE EXTENSION IF NOT EXISTS "citext";

CREATE TABLE clientes (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    razao_social VARCHAR(150) NOT NULL,
    nome_fantasia VARCHAR(100) NOT NULL,
    cnpj VARCHAR(18) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
    data_contratacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_clientes PRIMARY KEY (id),
    CONSTRAINT uq_clientes_cnpj UNIQUE (cnpj),
    CONSTRAINT ck_cliente_status CHECK (status IN ('ATIVO', 'BLOQUEADO', 'INATIVO'))
);

CREATE TABLE departamentos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    codigo_sigla VARCHAR(20) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    id_responsavel INT,
    id_departamento_pai INT,
    status VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
    data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_departamentos PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_departamentos_id UNIQUE (id),
    CONSTRAINT fk_depto_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_depto_pai FOREIGN KEY (id_cliente, id_departamento_pai) REFERENCES departamentos(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT uq_sigla_por_cliente UNIQUE (id_cliente, codigo_sigla),
    CONSTRAINT ck_depto_status CHECK (status IN ('ATIVO', 'INATIVO'))
);

CREATE TABLE usuarios (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    email CITEXT NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    id_departamento INT,
    cargo VARCHAR(100) NOT NULL,
    perfil VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
    avatar_url VARCHAR(255),
    data_cadastro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ultimo_login TIMESTAMPTZ,
    CONSTRAINT pk_usuarios PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_usuarios_id UNIQUE (id),
    CONSTRAINT uq_email_por_cliente UNIQUE (id_cliente, email),
    CONSTRAINT fk_usuario_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_usuario_depto FOREIGN KEY (id_cliente, id_departamento) REFERENCES departamentos(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT ck_usuario_status CHECK (status IN ('ATIVO', 'DESATIVADO', 'PENDENTE_CONFIRMACAO')),
    CONSTRAINT ck_usuario_perfil CHECK (perfil IN ('ADMIN', 'GESTOR', 'TECNICO', 'SOLICITANTE'))
);

ALTER TABLE departamentos ADD CONSTRAINT fk_depto_responsavel FOREIGN KEY (id_cliente, id_responsavel) REFERENCES usuarios(id_cliente, id) ON DELETE RESTRICT;

CREATE TABLE grupos_suporte (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
    data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_grupos_suporte PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_grupos_suporte_id UNIQUE (id),
    CONSTRAINT fk_grupo_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT ck_grupo_status CHECK (status IN ('ATIVO', 'INATIVO')),
    CONSTRAINT uq_nome_grupo_por_cliente UNIQUE (id_cliente, nome)
);

CREATE TABLE membros_grupos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_grupo INT NOT NULL,
    id_usuario INT NOT NULL,
    cargo_especialidade VARCHAR(100),
    carga_trabalho_max INT NOT NULL DEFAULT 100,
    data_associacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_membros_grupos PRIMARY KEY (id_cliente, id),
    CONSTRAINT fk_membros_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_membros_grupo FOREIGN KEY (id_cliente, id_grupo) REFERENCES grupos_suporte(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT fk_membros_usuario FOREIGN KEY (id_cliente, id_usuario) REFERENCES usuarios(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT uq_membro_grupo UNIQUE (id_cliente, id_grupo, id_usuario),
    CONSTRAINT ck_membro_carga CHECK (carga_trabalho_max BETWEEN 0 AND 100)
);

CREATE TABLE categorias_chamados (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    id_categoria_pai INT,
    tipo_aplicacao VARCHAR(20) NOT NULL DEFAULT 'AMBOS',
    status VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
    data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_categorias_chamados PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_categorias_chamados_id UNIQUE (id),
    CONSTRAINT fk_cat_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_cat_pai FOREIGN KEY (id_cliente, id_categoria_pai) REFERENCES categorias_chamados(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT ck_cat_status CHECK (status IN ('ATIVO', 'INATIVO')),
    CONSTRAINT ck_cat_tipo CHECK (tipo_aplicacao IN ('INCIDENTE', 'REQUISICAO', 'AMBOS'))
);

CREATE TABLE horarios_comerciais (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    fuso_horario VARCHAR(50) NOT NULL DEFAULT 'America/Cuiaba',
    status VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
    data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_horarios_comerciais PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_horarios_comerciais_id UNIQUE (id),
    CONSTRAINT fk_hc_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT ck_hc_status CHECK (status IN ('ATIVO', 'INATIVO'))
);

CREATE TABLE intervalos_horarios (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_horario_comercial INT NOT NULL,
    dia_semana INT NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fim TIME NOT NULL,
    CONSTRAINT pk_intervalos_horarios PRIMARY KEY (id_cliente, id),
    CONSTRAINT fk_ih_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_ih_horario FOREIGN KEY (id_cliente, id_horario_comercial) REFERENCES horarios_comerciais(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT ck_ih_dia CHECK (dia_semana BETWEEN 0 AND 6),
    CONSTRAINT ck_ih_horas CHECK (hora_fim > hora_inicio)
);

CREATE TABLE feriados (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    dia INT NOT NULL,
    mes INT NOT NULL,
    ano INT,
    CONSTRAINT pk_feriados PRIMARY KEY (id_cliente, id),
    CONSTRAINT fk_feriados_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT ck_feriado_dia CHECK (dia BETWEEN 1 AND 31),
    CONSTRAINT ck_feriado_mes CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT ck_feriado_ano CHECK (ano >= 2000)
);

CREATE TABLE politicas_sla (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    prioridade_alvo VARCHAR(20) NOT NULL,
    tipo_chamado_alvo VARCHAR(20) NOT NULL,
    tempo_resposta_min INT NOT NULL,
    tempo_resolucao_min INT NOT NULL,
    id_horario_comercial INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
    CONSTRAINT pk_politicas_sla PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_politicas_sla_id UNIQUE (id),
    CONSTRAINT fk_sla_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_sla_horario FOREIGN KEY (id_cliente, id_horario_comercial) REFERENCES horarios_comerciais(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT ck_sla_status CHECK (status IN ('ATIVO', 'INATIVO')),
    CONSTRAINT ck_sla_prioridade CHECK (prioridade_alvo IN ('CRITICA', 'ALTA', 'MEDIA', 'BAIXA')),
    CONSTRAINT ck_sla_tipo CHECK (tipo_chamado_alvo IN ('INCIDENTE', 'REQUISICAO', 'AMBOS')),
    CONSTRAINT ck_sla_tempos CHECK (tempo_resposta_min >= 0 AND tempo_resolucao_min > 0)
);

CREATE TABLE chamados (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_solicitante INT NOT NULL,
    id_tecnico_atribuido INT,
    id_grupo_responsavel INT,
    id_categoria INT NOT NULL,
    id_politica_sla INT,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    origem VARCHAR(20) NOT NULL DEFAULT 'PORTAL',
    prioridade VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'NOVO',
    data_abertura TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data_previsao_resolucao TIMESTAMPTZ,
    data_resolucao TIMESTAMPTZ,
    data_fechamento TIMESTAMPTZ,
    resolucao TEXT,
    tempo_acumulado_pausa_s INT NOT NULL DEFAULT 0,
    sla_vencido BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_chamados PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_chamados_id UNIQUE (id),
    CONSTRAINT fk_chamado_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_chamado_solicitante FOREIGN KEY (id_cliente, id_solicitante) REFERENCES usuarios(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT fk_chamado_tecnico FOREIGN KEY (id_cliente, id_tecnico_atribuido) REFERENCES usuarios(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT fk_chamado_grupo FOREIGN KEY (id_cliente, id_grupo_responsavel) REFERENCES grupos_suporte(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT fk_chamado_categoria FOREIGN KEY (id_cliente, id_categoria) REFERENCES categorias_chamados(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT fk_chamado_sla FOREIGN KEY (id_cliente, id_politica_sla) REFERENCES politicas_sla(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT ck_chamado_tipo CHECK (tipo IN ('INCIDENTE', 'REQUISICAO')),
    CONSTRAINT ck_chamado_origem CHECK (origem IN ('PORTAL', 'TELEFONE', 'EMAIL', 'CHAT', 'API')),
    CONSTRAINT ck_chamado_prioridade CHECK (prioridade IN ('CRITICA', 'ALTA', 'MEDIA', 'BAIXA')),
    CONSTRAINT ck_chamado_status CHECK (status IN ('NOVO', 'EM_ATENDIMENTO', 'PENDENTE', 'RESOLVIDO', 'CONCLUIDO')),
    CONSTRAINT ck_chamado_tempo_pausa CHECK (tempo_acumulado_pausa_s >= 0),
    CONSTRAINT ck_chamados_datas CHECK (
        (data_resolucao IS NULL OR data_resolucao >= data_abertura) AND
        (data_fechamento IS NULL OR data_fechamento >= data_abertura) AND
        (data_fechamento IS NULL OR data_resolucao IS NOT NULL) AND
        (data_fechamento IS NULL OR data_resolucao IS NULL OR data_fechamento >= data_resolucao)
    )
);

CREATE TABLE comentarios_chamados (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_chamado INT NOT NULL,
    id_autor INT NOT NULL,
    mensagem TEXT NOT NULL,
    tipo_visibilidade VARCHAR(20) NOT NULL DEFAULT 'PUBLICO',
    data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_comentarios_chamados PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_comentarios_chamados_id UNIQUE (id),
    CONSTRAINT fk_com_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_com_chamado FOREIGN KEY (id_cliente, id_chamado) REFERENCES chamados(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT fk_com_autor FOREIGN KEY (id_cliente, id_autor) REFERENCES usuarios(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT ck_com_visibilidade CHECK (tipo_visibilidade IN ('PUBLICO', 'INTERNO'))
);

CREATE TABLE anexos_chamados (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_chamado INT NOT NULL,
    id_comentario INT,
    nome_arquivo VARCHAR(255) NOT NULL,
    caminho_storage VARCHAR(512) NOT NULL,
    tipo_mime VARCHAR(100) NOT NULL,
    tamanho_bytes BIGINT NOT NULL,
    conteudo BYTEA,
    data_upload TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_anexos_chamados PRIMARY KEY (id_cliente, id),
    CONSTRAINT fk_anexo_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_anexo_chamado FOREIGN KEY (id_cliente, id_chamado) REFERENCES chamados(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT fk_anexo_comentario FOREIGN KEY (id_cliente, id_comentario) REFERENCES comentarios_chamados(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT ck_anexo_tamanho CHECK (tamanho_bytes > 0 AND tamanho_bytes <= 20971520)
);

CREATE TABLE worklogs (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_chamado INT NOT NULL,
    id_tecnico INT NOT NULL,
    descricao_atividade TEXT NOT NULL,
    tempo_trabalhado_min INT NOT NULL,
    data_execucao TIMESTAMPTZ NOT NULL,
    data_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_worklogs PRIMARY KEY (id_cliente, id),
    CONSTRAINT fk_wl_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_wl_chamado FOREIGN KEY (id_cliente, id_chamado) REFERENCES chamados(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT fk_wl_tecnico FOREIGN KEY (id_cliente, id_tecnico) REFERENCES usuarios(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT ck_wl_tempo CHECK (tempo_trabalhado_min > 0)
);

CREATE TABLE historico_status_chamados (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_chamado INT NOT NULL,
    status_anterior VARCHAR(30),
    status_novo VARCHAR(30) NOT NULL,
    id_usuario_alterou INT NOT NULL,
    data_alteracao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    tempo_no_status_seg INT,
    CONSTRAINT pk_historico_status PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_historico_status_id UNIQUE (id),
    CONSTRAINT fk_hist_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_hist_chamado FOREIGN KEY (id_cliente, id_chamado) REFERENCES chamados(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT fk_hist_usuario FOREIGN KEY (id_cliente, id_usuario_alterou) REFERENCES usuarios(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT ck_hist_status_ant CHECK (status_anterior IN ('NOVO', 'EM_ATENDIMENTO', 'PENDENTE', 'RESOLVIDO', 'CONCLUIDO')),
    CONSTRAINT ck_hist_status_novo CHECK (status_novo IN ('NOVO', 'EM_ATENDIMENTO', 'PENDENTE', 'RESOLVIDO', 'CONCLUIDO')),
    CONSTRAINT ck_hist_tempo CHECK (tempo_no_status_seg IS NULL OR tempo_no_status_seg >= 0)
);

CREATE TABLE pausas_sla (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_chamado INT NOT NULL,
    id_historico_origem INT NOT NULL,
    motivo_pausa VARCHAR(50) NOT NULL,
    data_pausa TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data_retomada TIMESTAMPTZ,
    tempo_pausado_seg INT,
    CONSTRAINT pk_pausas_sla PRIMARY KEY (id_cliente, id),
    CONSTRAINT fk_pausa_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_pausa_chamado FOREIGN KEY (id_cliente, id_chamado) REFERENCES chamados(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT fk_pausa_hist FOREIGN KEY (id_cliente, id_historico_origem) REFERENCES historico_status_chamados(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT ck_pausa_motivo CHECK (motivo_pausa IN ('AGUARDANDO_SOLICITANTE', 'AGUARDANDO_TERCEIRO', 'FORNECEDOR_EXTERNO', 'MANUTENCAO_PROGRAMADA')),
    CONSTRAINT ck_pausa_tempo CHECK (tempo_pausado_seg IS NULL OR tempo_pausado_seg >= 0),
    CONSTRAINT ck_pausa_datas CHECK (data_retomada IS NULL OR data_retomada >= data_pausa)
);

CREATE TABLE pesquisas_csat (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_chamado INT NOT NULL,
    id_solicitante INT NOT NULL,
    nota_satisfacao INT NOT NULL,
    comentarios TEXT,
    data_resposta TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_pesquisas_csat PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_csat_chamado UNIQUE (id_cliente, id_chamado),
    CONSTRAINT fk_csat_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_csat_chamado FOREIGN KEY (id_cliente, id_chamado) REFERENCES chamados(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT fk_csat_usuario FOREIGN KEY (id_cliente, id_solicitante) REFERENCES usuarios(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT ck_csat_nota CHECK (nota_satisfacao BETWEEN 1 AND 5)
);

CREATE TABLE problemas (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL,
    id_tecnico_atribuido INT,
    causa_raiz TEXT,
    solucao_contorno TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'SOB_INVESTIGACAO',
    prioridade VARCHAR(20) NOT NULL,
    data_identificacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data_resolucao TIMESTAMPTZ,
    CONSTRAINT pk_problemas PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_problemas_id UNIQUE (id),
    CONSTRAINT fk_prob_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_prob_tecnico FOREIGN KEY (id_cliente, id_tecnico_atribuido) REFERENCES usuarios(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT ck_prob_status CHECK (status IN ('SOB_INVESTIGACAO', 'ERRO_CONHECIDO', 'RESOLVIDO', 'FECHADO')),
    CONSTRAINT ck_prob_prioridade CHECK (prioridade IN ('CRITICA', 'ALTA', 'MEDIA', 'BAIXA'))
);

CREATE TABLE mudancas (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL,
    justificativa TEXT NOT NULL,
    plano_impacto TEXT NOT NULL,
    plano_testes TEXT NOT NULL,
    plano_retorno TEXT NOT NULL,
    tipo_mudanca VARCHAR(20) NOT NULL,
    id_solicitante INT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'RASCUNHO',
    janela_inicio TIMESTAMPTZ NOT NULL,
    janela_fim TIMESTAMPTZ NOT NULL,
    data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_mudancas PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_mudancas_id UNIQUE (id),
    CONSTRAINT fk_mud_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_mud_solicitante FOREIGN KEY (id_cliente, id_solicitante) REFERENCES usuarios(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT ck_mud_tipo CHECK (tipo_mudanca IN ('PADRAO', 'NORMAL', 'EMERGENCIAL')),
    CONSTRAINT ck_mud_status CHECK (status IN ('RASCUNHO', 'AVALIACAO', 'APROVACAO', 'AGENDADA', 'EM_IMPLEMENTACAO', 'CONCLUIDA', 'CANCELADA')),
    CONSTRAINT ck_mud_janela CHECK (janela_fim > janela_inicio)
);

CREATE TABLE chamados_problemas (
    id_cliente INT NOT NULL,
    id_chamado INT NOT NULL,
    id_problema INT NOT NULL,
    data_vinculo TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_chamados_problemas PRIMARY KEY (id_cliente, id_chamado, id_problema),
    CONSTRAINT fk_cp_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_cp_chamado FOREIGN KEY (id_cliente, id_chamado) REFERENCES chamados(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT fk_cp_problema FOREIGN KEY (id_cliente, id_problema) REFERENCES problemas(id_cliente, id) ON DELETE CASCADE
);

CREATE TABLE mudancas_chamados (
    id_cliente INT NOT NULL,
    id_mudanca INT NOT NULL,
    id_chamado INT NOT NULL,
    data_vinculo TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_mudancas_chamados PRIMARY KEY (id_cliente, id_mudanca, id_chamado),
    CONSTRAINT fk_mc_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_mc_mudanca FOREIGN KEY (id_cliente, id_mudanca) REFERENCES mudancas(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT fk_mc_chamado FOREIGN KEY (id_cliente, id_chamado) REFERENCES chamados(id_cliente, id) ON DELETE CASCADE
);

CREATE TABLE mudancas_problemas (
    id_cliente INT NOT NULL,
    id_mudanca INT NOT NULL,
    id_problema INT NOT NULL,
    data_vinculo TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_mudancas_problemas PRIMARY KEY (id_cliente, id_mudanca, id_problema),
    CONSTRAINT fk_mp_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_mp_mudanca FOREIGN KEY (id_cliente, id_mudanca) REFERENCES mudancas(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT fk_mp_problema FOREIGN KEY (id_cliente, id_problema) REFERENCES problemas(id_cliente, id) ON DELETE CASCADE
);

CREATE TABLE ativos_cmdb (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    codigo_patrimonio VARCHAR(50) NOT NULL,
    nome VARCHAR(150) NOT NULL,
    tipo_ativo VARCHAR(30) NOT NULL,
    id_usuario_atribuido INT,
    status VARCHAR(30) NOT NULL DEFAULT 'ATIVO',
    data_aquisicao DATE,
    data_cadastro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_ativos_cmdb PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_ativos_cmdb_id UNIQUE (id),
    CONSTRAINT fk_ativo_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_ativo_usuario FOREIGN KEY (id_cliente, id_usuario_atribuido) REFERENCES usuarios(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT uq_patrimonio_cliente UNIQUE (id_cliente, codigo_patrimonio),
    CONSTRAINT ck_ativo_status CHECK (status IN ('ATIVO', 'EM_MANUTENCAO', 'DESATIVADO', 'EM_ESTOQUE')),
    CONSTRAINT ck_ativo_tipo CHECK (tipo_ativo IN ('NOTEBOOK', 'SERVIDOR', 'LICENCA_SOFTWARE', 'RUST_ROUTER', 'SWITCH', 'OUTRO'))
);

CREATE TABLE especificacoes_ativos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_ativo INT NOT NULL,
    chave_propriedade VARCHAR(100) NOT NULL,
    valor VARCHAR(255) NOT NULL,
    CONSTRAINT pk_especificacoes PRIMARY KEY (id_cliente, id),
    CONSTRAINT fk_espec_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_espec_ativo FOREIGN KEY (id_cliente, id_ativo) REFERENCES ativos_cmdb(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT uq_espec_propriedade_cliente UNIQUE (id_cliente, id_ativo, chave_propriedade)
);

CREATE TABLE historicos_manutencao_ativos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_ativo INT NOT NULL,
    id_tecnico INT NOT NULL,
    descricao_servico TEXT NOT NULL,
    custo_manutencao NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    data_inicio TIMESTAMPTZ NOT NULL,
    data_fim TIMESTAMPTZ,
    CONSTRAINT pk_historico_manutencao PRIMARY KEY (id_cliente, id),
    CONSTRAINT fk_manut_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_manut_ativo FOREIGN KEY (id_cliente, id_ativo) REFERENCES ativos_cmdb(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT fk_manut_tecnico FOREIGN KEY (id_cliente, id_tecnico) REFERENCES usuarios(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT ck_manut_custo CHECK (custo_manutencao >= 0.00),
    CONSTRAINT ck_manut_datas CHECK (data_fim IS NULL OR data_fim >= data_inicio)
);

CREATE TABLE chamados_ativos (
    id_cliente INT NOT NULL,
    id_chamado INT NOT NULL,
    id_ativo INT NOT NULL,
    CONSTRAINT pk_chamados_ativos PRIMARY KEY (id_cliente, id_chamado, id_ativo),
    CONSTRAINT fk_ca_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_ca_chamado FOREIGN KEY (id_cliente, id_chamado) REFERENCES chamados(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT fk_ca_ativo FOREIGN KEY (id_cliente, id_ativo) REFERENCES ativos_cmdb(id_cliente, id) ON DELETE CASCADE
);

CREATE TABLE relacionamentos_ativos (
    id_cliente INT NOT NULL,
    id_ativo_origem INT NOT NULL,
    id_ativo_destino INT NOT NULL,
    tipo_relacionamento VARCHAR(50) NOT NULL,
    data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_relacionamentos_ativos PRIMARY KEY (id_cliente, id_ativo_origem, id_ativo_destino),
    CONSTRAINT fk_ra_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_ra_origem FOREIGN KEY (id_cliente, id_ativo_origem) REFERENCES ativos_cmdb(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT fk_ra_destino FOREIGN KEY (id_cliente, id_ativo_destino) REFERENCES ativos_cmdb(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT ck_auto_relacionamento CHECK (id_ativo_origem <> id_ativo_destino)
);

CREATE TABLE requisicoes_aprovacao (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_chamado INT,
    id_mudanca INT,
    id_solicitante INT NOT NULL,
    id_aprovador INT NOT NULL,
    descricao TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    justificativa_aprovador TEXT,
    data_solicitacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data_decisao TIMESTAMPTZ,
    CONSTRAINT pk_requisicoes_aprovacao PRIMARY KEY (id_cliente, id),
    CONSTRAINT fk_aprov_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_aprov_chamado FOREIGN KEY (id_cliente, id_chamado) REFERENCES chamados(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT fk_aprov_mudanca FOREIGN KEY (id_cliente, id_mudanca) REFERENCES mudancas(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT fk_aprov_solicitante FOREIGN KEY (id_cliente, id_solicitante) REFERENCES usuarios(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT fk_aprov_aprovador FOREIGN KEY (id_cliente, id_aprovador) REFERENCES usuarios(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT ck_aprov_status CHECK (status IN ('PENDENTE', 'APROVADO', 'REJEITADO', 'CANCELADO')),
    CONSTRAINT ck_objeto_aprovacao CHECK ( (id_chamado IS NOT NULL AND id_mudanca IS NULL) OR (id_chamado IS NULL AND id_mudanca IS NOT NULL) )
);

CREATE TABLE categorias_artigos_kb (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_categorias_kb PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_categorias_kb_id UNIQUE (id),
    CONSTRAINT fk_cat_kb_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT uq_cat_kb_nome_cliente UNIQUE (id_cliente, nome)
);

CREATE TABLE artigos_kb (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_categoria INT NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    conteudo TEXT NOT NULL,
    id_autor INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'RASCUNHO',
    visualizacoes INT NOT NULL DEFAULT 0,
    data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data_atualizacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_artigos_kb PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_artigos_kb_id UNIQUE (id),
    CONSTRAINT fk_art_kb_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_art_kb_categoria FOREIGN KEY (id_cliente, id_categoria) REFERENCES categorias_artigos_kb(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT fk_art_kb_autor FOREIGN KEY (id_cliente, id_autor) REFERENCES usuarios(id_cliente, id) ON DELETE RESTRICT,
    CONSTRAINT ck_art_kb_status CHECK (status IN ('RASCUNHO', 'REVISAO', 'PUBLICADO', 'ARQUIVADO')),
    CONSTRAINT ck_art_kb_views CHECK (visualizacoes >= 0)
);

CREATE TABLE feedbacks_artigos_kb (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_artigo INT NOT NULL,
    id_usuario INT NOT NULL,
    util BOOLEAN NOT NULL,
    comentario TEXT,
    data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_feedbacks_kb PRIMARY KEY (id_cliente, id),
    CONSTRAINT fk_fb_kb_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_fb_kb_artigo FOREIGN KEY (id_cliente, id_artigo) REFERENCES artigos_kb(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT fk_fb_kb_usuario FOREIGN KEY (id_cliente, id_usuario) REFERENCES usuarios(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT uq_feedback_usuario UNIQUE (id_cliente, id_artigo, id_usuario)
);

CREATE TABLE notificacoes (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_usuario INT NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    mensagem TEXT NOT NULL,
    lida BOOLEAN NOT NULL DEFAULT FALSE,
    data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_notificacoes PRIMARY KEY (id_cliente, id),
    CONSTRAINT fk_notif_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_notif_usuario FOREIGN KEY (id_cliente, id_usuario) REFERENCES usuarios(id_cliente, id) ON DELETE CASCADE
);

CREATE TABLE logs_auditoria (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_usuario INT,
    acao VARCHAR(100) NOT NULL,
    tabela_afetada VARCHAR(100) NOT NULL,
    registro_id INT,
    valor_anterior JSONB,
    valor_novo JSONB,
    endereco_ip VARCHAR(45),
    data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_logs_auditoria PRIMARY KEY (id_cliente, id),
    CONSTRAINT fk_auditoria_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_auditoria_usuario FOREIGN KEY (id_cliente, id_usuario) REFERENCES usuarios(id_cliente, id) ON DELETE RESTRICT
);

CREATE TABLE configuracoes_branding (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    logo_url VARCHAR(255),
    cor_primaria VARCHAR(7) DEFAULT '#0056B3',
    cor_secundaria VARCHAR(7) DEFAULT '#6C757D',
    cor_fundo VARCHAR(7) DEFAULT '#F4F6F9',
    nome_portal VARCHAR(100) DEFAULT 'Service Desk',
    CONSTRAINT pk_branding PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_branding_cliente UNIQUE (id_cliente),
    CONSTRAINT fk_branding_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE
);

CREATE TABLE integracoes (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    configuracoes JSONB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
    data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_integracoes PRIMARY KEY (id_cliente, id),
    CONSTRAINT uq_integracoes_id UNIQUE (id),
    CONSTRAINT fk_integracoes_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT uq_nome_integracao_cliente UNIQUE (id_cliente, nome),
    CONSTRAINT ck_integracao_status CHECK (status IN ('ATIVO', 'INATIVO'))
);

CREATE TABLE historico_integracoes (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT NOT NULL,
    id_integracao INT NOT NULL,
    tipo_evento VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    dados_log TEXT,
    data_execucao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_historico_integracoes PRIMARY KEY (id_cliente, id),
    CONSTRAINT fk_log_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_log_integracao FOREIGN KEY (id_cliente, id_integracao) REFERENCES integracoes(id_cliente, id) ON DELETE CASCADE,
    CONSTRAINT ck_log_status CHECK (status IN ('SUCESSO', 'FALHA', 'EM_ANDAMENTO'))
);

CREATE OR REPLACE FUNCTION fn_check_intervalo_sobreposicao()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM intervalos_horarios
        WHERE id_cliente = NEW.id_cliente
          AND id_horario_comercial = NEW.id_horario_comercial
          AND dia_semana = NEW.dia_semana
          AND id <> NEW.id
          AND (
              (NEW.hora_inicio, NEW.hora_fim) OVERLAPS (hora_inicio, hora_fim)
          )
    ) THEN
        RAISE EXCEPTION 'Sobreposição de horário detectada para o dia da semana % no horário comercial %.', NEW.dia_semana, NEW.id_horario_comercial;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_check_intervalo_sobreposicao
BEFORE INSERT OR UPDATE ON intervalos_horarios
FOR EACH ROW EXECUTE FUNCTION fn_check_intervalo_sobreposicao();

CREATE OR REPLACE FUNCTION fn_impedir_alteracao_auditoria()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'A tabela de logs de auditoria é imutável para o usuário da aplicação. Operações de UPDATE, DELETE ou TRUNCATE são estritamente proibidas para conformidade forense.';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_prevent_update_delete_auditoria
BEFORE UPDATE OR DELETE OR TRUNCATE ON logs_auditoria
FOR EACH STATEMENT EXECUTE FUNCTION fn_impedir_alteracao_auditoria();

CREATE INDEX idx_chamados_cliente_status_prioridade ON chamados(id_cliente, status, prioridade);
CREATE INDEX idx_chamados_cliente_solicitante ON chamados(id_cliente, id_solicitante);
CREATE INDEX idx_chamados_cliente_tecnico ON chamados(id_cliente, id_tecnico_atribuido);
CREATE INDEX idx_chamados_cliente_grupo ON chamados(id_cliente, id_grupo_responsavel);
CREATE INDEX idx_chamados_cliente_categoria ON chamados(id_cliente, id_categoria);
CREATE INDEX idx_hist_status_chamado_composto ON historico_status_chamados(id_cliente, id_chamado, data_alteracao);
CREATE INDEX idx_pausas_sla_chamado_composto ON pausas_sla(id_cliente, id_chamado) WHERE data_retomada IS NULL;
CREATE INDEX idx_artigos_kb_categoria ON artigos_kb(id_cliente, id_categoria);
CREATE INDEX idx_ativos_usuario ON ativos_cmdb(id_cliente, id_usuario_atribuido);
CREATE INDEX idx_ativos_patrimonio ON ativos_cmdb(id_cliente, codigo_patrimonio);
CREATE INDEX idx_logs_auditoria_composto ON logs_auditoria(id_cliente, data_criacao);
CREATE UNIQUE INDEX uq_feriado_pontual_cliente ON feriados(id_cliente, dia, mes, ano) WHERE ano IS NOT NULL;
CREATE UNIQUE INDEX uq_feriado_recorrente_cliente ON feriados(id_cliente, dia, mes) WHERE ano IS NULL;
